services:
  mysql:
    build:
      context: ./resources/docker/mysql
    image: mysql-server:${DOCKER_PROJECT:-api}
    container_name: db-${DOCKER_PROJECT:-mysql}
    environment:
      MYSQL_DATABASE: ${DB_NAME:-apidb}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Adm1ns}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-Adm1ns}
    ports:
      - "${DB_PORT:-3306}:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
    restart: always
  php:
    build:
      context: ./resources/docker/php
    image: php-server:${DOCKER_PROJECT:-api}
    container_name: api-${DOCKER_PROJECT:-php}
    ports:
      - "${PHP_PORT:-80}:80"
    volumes:
      - ${PWD}:/var/www/html
    links:
      - mysql
